### PR TITLE
Added iCal support for appointments

### PR DESCRIPTION
**Pull request by alanzhangithub**
Added iCal download for appointments. Users can gen and get .ics files for each appt via appt page. Download button also attached.

### CODE REVIEW

**Review by 1ptqc-KD-97bsBG-pVJG — DISMISSED** [review]

**Review by 1ptqc-KD-97bsBG-pVJG — CHANGES_REQUESTED** [review]
All the code looks good to me and the download button produces a file. However, I am unable to get anything to open the iCal file. Guessing the file isn't being written right. Please take a look if possible. If it's determined to not be an easy fix we can just merge it. Demoing by just downloading the file should be enough.
image

**Comment by alanzhangithub** [comment]
I wasn't handling the service right under app/service

**Review by UrBoiEvan — DISMISSED** [review]
Code looks good to me. Ready to merge.

**Review by 1ptqc-KD-97bsBG-pVJG — CHANGES_REQUESTED** [review]
ical is readable now, but looks like the date field is incorrect and defaulting to January 1st, 2000. Please take another look. I also see some code mentioning projects, when I think we should really only be creating calendar events for appointments, please double check this too. Thanks!
image
image

**Review by 1ptqc-KD-97bsBG-pVJG — APPROVED** [review]

**Pull request merged**
